### ISSUE TITLE
Split into multiple artifacts on maven central

### ISSUE THREAD

**Issue by calvertdw** [mihnita/java-color-loggers#6]
The problem with this library is that it pulls log4j and logback whether or not you need them. This can cause issues where they fight each other.

**Comment by mihnita** [comment]
Thanks, that kind of bothered me for a while too.
_But I was thinking "if nobody complains, then maybe is not an issue"_ :-)

Working on it (I had a few commits already).
Want to do a bite more cleanup, but will push a new release soon(ish)

**Comment by mihnita** [comment]
Done, version 10.0.7 has 3 modules, split per logger, with minimal dependencies.

In theory I can split is further to have versions with / without jansi, but it is a bit too much maintenance...
