### ISSUE TITLE
No stack trance log

### ISSUE THREAD

**Issue by missYouSmile** [mihnita/java-color-loggers#8]
HI,  I use your color-loggers its fine.But I found problem when log params contains Exception Object. It can not print the exception stack trace log. 
I used spring-boot-starter-log4j + lombok, and the Appender is com.mihnita.colorlog.log4j.AnsiColorConsoleAppender.
I found the method subAppend() is covered when I read the source of AnsiColorConsoleAppender. May be this is the problem.
Wish your reply, thanks!

**Comment by mihnita** [comment]
What is you pattern in the configuration file?
It should contain %throwable. I've added it to my config and it works.

That is a jog4j thing, nothing to do with the color logger.

See the documentation here:
    https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/EnhancedPatternLayout.html

**Comment by mihnita** [comment]
Works, seems to be a configuration problem.
